version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1.2
  node: circleci/node@7.0.0
parameters:
  working-dir:
	type: string
	default: ~/project/infra
jobs:
  build:
	docker:
  	- image: cimg/node:22.12.0
	working_directory: << pipeline.parameters.working-dir >>
	steps:
  	- checkout:
      	path: ~/project
  	- node/install-packages:
      	with-cache: true
  	- run:
      	name: Audit and Fix Dependencies
      	command: |
        	npm audit || true # Log vulnerabilities but don't fail the build
        	npm audit fix 	# Attempt to fix vulnerabilities
  	- run:
      	name: Run Synth
      	command: npm run synth
  	- persist_to_workspace:
      	root: ~/project
      	paths:
        	- .
  test:
	docker:
  	- image: cimg/node:22.12.0
	working_directory: << pipeline.parameters.working-dir >>
	steps:
  	- attach_workspace:
      	at: ~/project
  	- run:
      	name: Run Tests
      	command: npm run test
  	- store_test_results:
      	path: << pipeline.parameters.working-dir >>/reports
  	- store_artifacts:
      	path: << pipeline.parameters.working-dir >>/reports
  deploy:
	docker:
  	- image: cimg/aws:2024.03
	working_directory: << pipeline.parameters.working-dir >>
	steps:
  	- attach_workspace:
      	at: ~/project
  	- aws-cli/setup:
      	role_arn: ${OIDC_ROLE_ARN}
      	region: ${AWS_REGION}
  	- run:
      	name: Get Caller Identity
      	command: |
        	aws sts get-caller-identity
  	- setup_remote_docker:
      	docker_layer_caching: true
  	- run:
      	name: Deploy CDK Application
      	command: |
        	npm run deploy
workflows:
  build-deploy-pipeline:
	jobs:
  	- build
  	- test:
      	requires:
        	- build
  	- deploy:
      	requires:
        	- test
